name: scrolls_to_top
description: A dart package for working with scrolls-to-top iOS feature. Easy to use
version: 1.0.2
homepage: https://github.com/optimist-dev/scrolls_to_top

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.3
  flutter_test:
    sdk: flutter